name: Deploy Backend to Firebase

on:
  push:
    branches: [ "master" ]
  pull_request: 
    branches: [ "master" ]
     
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend  # Set the default working directory to 'Backend' for all run steps
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  
        working-directory: Backend

    - name: Install Dependencies
      run: npm install
      working-directory: Backend
      
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./Backend